// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBd2UUskqxNOF9jXvBpnRETFtTBVWUydeA',
    appId: '1:416302423771:web:b4c113fb5e5084f449b6fe',
    messagingSenderId: '416302423771',
    projectId: 'cowboy-9bf1f',
    authDomain: 'cowboy-9bf1f.firebaseapp.com',
    storageBucket: 'cowboy-9bf1f.firebasestorage.app',
    measurementId: 'G-T03GJM2PC8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6Qh5vtNra-mGQR9hUEPX8c9DiZM8rnbM',
    appId: '1:416302423771:android:63a3a1320c6341b649b6fe',
    messagingSenderId: '416302423771',
    projectId: 'cowboy-9bf1f',
    storageBucket: 'cowboy-9bf1f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBH73pRnqv8rRwGOO_v_bXa0YweoIbImD8',
    appId: '1:416302423771:ios:5ef8ad85c575d87149b6fe',
    messagingSenderId: '416302423771',
    projectId: 'cowboy-9bf1f',
    storageBucket: 'cowboy-9bf1f.firebasestorage.app',
    iosBundleId: 'com.west.dedicatedCowboy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBH73pRnqv8rRwGOO_v_bXa0YweoIbImD8',
    appId: '1:416302423771:ios:f49e55229e0574be49b6fe',
    messagingSenderId: '416302423771',
    projectId: 'cowboy-9bf1f',
    storageBucket: 'cowboy-9bf1f.firebasestorage.app',
    iosBundleId: 'com.example.dedicatedCowboy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBd2UUskqxNOF9jXvBpnRETFtTBVWUydeA',
    appId: '1:416302423771:web:f684533c84f6511949b6fe',
    messagingSenderId: '416302423771',
    projectId: 'cowboy-9bf1f',
    authDomain: 'cowboy-9bf1f.firebaseapp.com',
    storageBucket: 'cowboy-9bf1f.firebasestorage.app',
    measurementId: 'G-ZLZCJYF4EX',
  );

}